version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: rocker/r-ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installation (APT)
          command: |
            apt-get update
            apt-get install --yes \
              git \
              r-cran-bookdown \
              r-cran-fs \
              r-cran-rmarkdown \
              r-cran-rstudioapi \
              r-cran-xml2
      - run:
          name: Installation (CRAN)
          command: |
            Rscript -e 'install.packages("distill")'
      - run:
          name: Build site
          command: Rscript build.R
      - store_artifacts:
          path: public/
