version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: rocker/r-ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installation (APT)
          command: |
            apt-get update
            apt-get upgrade --yes
            apt-get install --yes \
              git \
              r-cran-bookdown \
              r-cran-fs \
              r-cran-git2r \
              r-cran-rmarkdown \
              r-cran-rstudioapi \
              r-cran-xml2
      - run:
          name: Install pandoc 2+ (required for distill pkg)
          command: |
            ver=2.7
            url="https://github.com/jgm/pandoc/releases/download/${ver}/pandoc-${ver}-1-amd64.deb"
            wget -P /tmp $url
            dpkg -i /tmp/pandoc-${ver}-1-amd64.deb
            pandoc -v
      - run:
          name: Installation (CRAN)
          command: Rscript -e 'install.packages("distill")'
      - run:
          name: Session information
          command: Rscript -e 'sessionInfo()'
      - run:
          name: Build site
          command: Rscript build-ci.R
      - add_ssh_keys:
          fingerprints:
            - "95:bb:ad:17:bc:a1:29:08:e2:0c:e5:2a:26:f9:39:e2"
      - run:
          name: Commit and push changes
          command: |
            last_committer=`git log -n 1 --format='%cn'`
            if [[ "${CI}" = "true" &&
                  "${CIRCLECI}" = "true" &&
                  "${CIRCLE_USERNAME}" = "jdblischak" &&
                  -z "${CIRCLE_PULL_REQUEST}" &&
                  ${last_committer} != "CircleCI Job"
               ]]
            then
              echo "Committing and pushing to GitHub"
              git config --global user.email "jdblischak@gmail.com"
              git config --global user.name "CircleCI Job"
              git checkout master
              git add _posts/ public/
              git commit -a --allow-empty -m "Blog built from ${CIRCLE_SHA1} on `date --rfc-3339=s`"
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              git push origin master
            else
              echo "The changes were not committed"
            fi
      - store_artifacts:
          path: public/
